-- import to SQLite by running: sqlite3.exe db.sqlite3 -init sqlite.sql
PRAGMA foreign_keys = ON;
BEGIN TRANSACTION;

CREATE TABLE `Role` (
`id` INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL UNIQUE,
`role` TEXT NOT NULL UNIQUE
);

CREATE TABLE `User` (
`id` INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL UNIQUE,
`username` TEXT NOT NULL UNIQUE,
`hashedPassword` TEXT NOT NULL,
`roleId` INTEGER NOT NULL,
`createdAt` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
FOREIGN KEY (`roleId`) REFERENCES `Role`(`id`) ON DELETE CASCADE
);

CREATE TABLE `Category` (
`id` INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL UNIQUE,
`name` TEXT NOT NULL UNIQUE,
`description` TEXT
);

CREATE TABLE `Product` (
`id` INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL UNIQUE,
`name` TEXT NOT NULL,
`price` FLOAT NOT NULL,
`stock` INTEGER NOT NULL,
`createdAt` DATE NOT NULL DEFAULT CURRENT_TIMESTAMP,
`categoryId` INTEGER NOT NULL,
FOREIGN KEY (`categoryId`) REFERENCES `Category`(`id`) ON DELETE CASCADE
);

CREATE TABLE `Token` (
`id` INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL UNIQUE,
`userId` INTEGER NOT NULL,
`key` TEXT NOT NULL,
FOREIGN KEY (`userId`) REFERENCES `User`(`id`) ON DELETE CASCADE
);


COMMIT;